- id: check-aml
  name: Validate Azure Machine Learning files consistency
  description: 'Validate inputs/outputs consistency of components/pipelines'
  entry: check-aml
  language: python
  types_or: [yaml]
  # we need types_or support
  minimum_pre_commit_version: 2.9.0
